In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(columns= ['Código', 'Natureza', 'Quantidade', 'Ativo', 'Preço', 'Garantia Disp'])

In [3]:
df

Empty DataFrame
Columns: [Código, Natureza, Quantidade, Ativo, Preço, Garantia Disp]
Index: []

In [4]:
dic_ordens = {}

In [5]:
arquivo = open("Ex_Clientes_Ordens.txt", "r")
novas_linhas = []

ordem = arquivo.readline()
while ordem != "":
    valores = ordem.strip().split(';')
    print(valores)

    novo_dado = {
        'Código': int(valores[0]),
        'Natureza': valores[1],
        'Quantidade': int(valores[2]),
        'Ativo': valores[3],
        'Preço': float(valores[4]),
        'Garantia Disp': float(valores[5])
    }
    

    novas_linhas.append(novo_dado)
    ordem = arquivo.readline()

arquivo.close()

df_novas_linhas = pd.DataFrame(novas_linhas)
df = pd.concat([df, df_novas_linhas], ignore_index=True)

print(df)

['2039221', 'C', '100', 'PETR4', '28', '100000']
['44534', 'C', '100', 'PETR4', '28', '120']
['226765', 'C', '10000', 'PETR4', '28', '20000']
['56542', 'C', '5000', 'MGLU3', '7', '20000']
['56564', 'C', '15000', 'MGLU3', '7', '10000']
['226765', 'C', '12000', 'MGLU3', '7', '100000']
['2039221', 'V', '100', 'PETR4', '28', '100000']
['44534', 'V', '100', 'PETR4', '28', '120']
['226765', 'V', '10000', 'PETR4', '28', '20000']
['56542', 'V', '5000', 'MGLU3', '7', '20000']
['56564', 'V', '15000', 'MGLU3', '7', '10000']
['226765', 'V', '12000', 'MGLU3', '7', '100000']
     Código Natureza Quantidade  Ativo  Preço  Garantia Disp
0   2039221        C        100  PETR4   28.0       100000.0
1     44534        C        100  PETR4   28.0          120.0
2    226765        C      10000  PETR4   28.0        20000.0
3     56542        C       5000  MGLU3    7.0        20000.0
4     56564        C      15000  MGLU3    7.0        10000.0
5    226765        C      12000  MGLU3    7.0       100000.0
6   2039221        V        100  PETR4   28.0       100000.0
7     44534        V        100  PETR4   28.0          120.0
8    226765        V      10000  PETR4   28.0        20000.0
9     56542        V       5000  MGLU3    7.0        20000.0
10    56564        V      15000  MGLU3    7.0        10000.0
11   226765        V      12000  MGLU3    7.0       100000.0

In [6]:
desagio = [0.05 if x == 'PETR4' else 0.1 for x in df['Ativo']]

In [7]:
df['Deságio'] = desagio

In [8]:
limite_fin = [100000 if x == 'PETR4' else 80000 for x in df['Ativo']]

In [9]:
df['Limite Boleta'] = limite_fin

In [10]:
df['Garantia Exigida'] = df['Quantidade']* df['Preço']*df['Deságio']

In [11]:
df['Resultado Garantia'] = df.apply(lambda row: 'Rejeitado' if row['Garantia Exigida'] > row['Garantia Disp'] else 'Aprovado', axis=1)

In [12]:
df['Volume Boleta'] = df['Quantidade'] * df['Preço']

In [13]:
df['Resultado Boleta'] = df.apply(lambda row: 'Rejeitado' if row['Volume Boleta'] > row['Limite Boleta'] else 'Aprovado', axis=1)

In [14]:
df

,Código,Natureza,Quantidade,Ativo,Preço,Garantia Disp,Deságio,Limite Boleta,Garantia Exigida,Resultado Garantia,Volume Boleta,Resultado Boleta
0,2039221,C,100,PETR4,28.0,100000.0,0.05,100000,140.0,Aprovado,2800.0,Aprovado
1,44534,C,100,PETR4,28.0,120.0,0.05,100000,140.0,Rejeitado,2800.0,Aprovado
2,226765,C,10000,PETR4,28.0,20000.0,0.05,100000,14000.0,Aprovado,280000.0,Rejeitado
3,56542,C,5000,MGLU3,7.0,20000.0,0.10,80000,3500.0,Aprovado,35000.0,Aprovado
4,56564,C,15000,MGLU3,7.0,10000.0,0.10,80000,10500.0,Rejeitado,105000.0,Rejeitado
5,226765,C,12000,MGLU3,7.0,100000.0,0.10,80000,8400.0,Aprovado,84000.0,Rejeitado
6,2039221,V,100,PETR4,28.0,100000.0,0.05,100000,140.0,Aprovado,2800.0,Aprovado
7,44534,V,100,PETR4,28.0,120.0,0.05,100000,140.0,Rejeitado,2800.0,Aprovado
8,226765,V,10000,PETR4,28.0,20000.0,0.05,100000,14000.0,Aprovado,280000.0,Rejeitado
9,56542,V,5000,MGLU3,7.0,20000.0,0.10,80000,3500.0,Aprovado,35000.0,Aprovado
10,56564,V,15000,MGLU3,7.0,10000.0,0.10,80000,10500.0,Rejeitado,105000.0,Rejeitado
11,226765,V,12000,MGLU3,7.0,100000.0,0.10,80000,8400.0,Aprovado,84000.0,Rejeitado

In [15]:
for index, row in df.iterrows():
    if row['Resultado Garantia'] == 'Rejeitado':
        print(f'ORDEM {row["Código"]} foi \033[31mrejeitada\033[m, pois garantia exigida ultrapassou a garantia disponível!')
    elif row['Resultado Boleta'] == 'Rejeitado':
        print(f'ORDEM {row["Código"]} foi \033[31mrejeitada\033[m, pois o volume financeiro da boleta ultrapassou o limite máximo definido')
    else:
        print(f'\033[32mORDEM {row["Código"]} foi enviada com sucesso!\033[m')

ORDEM 2039221 foi enviada com sucesso!
ORDEM 44534 foi rejeitada, pois garantia exigida ultrapassou a garantia disponível!
ORDEM 226765 foi rejeitada, pois o volume financeiro da boleta ultrapassou o limite máximo definido
ORDEM 56542 foi enviada com sucesso!
ORDEM 56564 foi rejeitada, pois garantia exigida ultrapassou a garantia disponível!
ORDEM 226765 foi rejeitada, pois o volume financeiro da boleta ultrapassou o limite máximo definido
ORDEM 2039221 foi enviada com sucesso!
ORDEM 44534 foi rejeitada, pois garantia exigida ultrapassou a garantia disponível!
ORDEM 226765 foi rejeitada, pois o volume financeiro da boleta ultrapassou o limite máximo definido
ORDEM 56542 foi enviada com sucesso!
ORDEM 56564 foi rejeitada, pois garantia exigida ultrapassou a garantia disponível!
ORDEM 226765 foi rejeitada, pois o volume financeiro da boleta ultrapassou o limite máximo definido

In [16]:
def organizar_ordens(nome_arquivo):
    df = pd.DataFrame(columns= ['Código', 'Natureza', 'Quantidade', 'Ativo', 'Preço', 'Garantia Disp'])
    arquivo = open(nome_arquivo, "r")
    novas_linhas = []

    # Ler linha por linha
    ordem = arquivo.readline()
    while ordem != "":
        # Dividir a ordem em seus dados
        valores = ordem.strip().split(';')
        # Criar um dicionário para a ordem
        novo_dado = {
            'Código': int(valores[0]),
            'Natureza': valores[1],
            'Quantidade': int(valores[2]),
            'Ativo': valores[3],
            'Preço': float(valores[4]),
            'Garantia Disp': float(valores[5])
        }

        # Adicionar o dicionário à lista de novas linhas
        novas_linhas.append(novo_dado)
        # Ler a próxima linha
        ordem = arquivo.readline()

    # Fechar o arquivo
    arquivo.close()

    # Converter a lista de dicionários em um DataFrame e concatenar com o DataFrame original
    df_novas_linhas = pd.DataFrame(novas_linhas)
    df = pd.concat([df, df_novas_linhas], ignore_index=True)
    
    # Cálculo/Inclusão das novas colunas necessárias
    desagio = [0.05 if x == 'PETR4' else 0.1 for x in df['Ativo']]
    df['Deságio'] = desagio
    limite_fin = [100000 if x == 'PETR4' else 80000 for x in df['Ativo']]
    df['Limite Boleta'] = limite_fin
    df['Garantia Exigida'] = df['Quantidade']* df['Preço']*df['Deságio']
    df['Resultado Garantia'] = df.apply(lambda row: 'Rejeitado' if row['Garantia Exigida'] > row['Garantia Disp'] else 'Aprovado', axis=1)
    df['Volume Boleta'] = df['Quantidade'] * df['Preço']
    df['Resultado Boleta'] = df.apply(lambda row: 'Rejeitado' if row['Volume Boleta'] > row['Limite Boleta'] else 'Aprovado', axis=1)
    
    
    
    return df

In [17]:
# Teste primeira func
organizar_ordens('Ex_Clientes_Ordens.txt')

,Código,Natureza,Quantidade,Ativo,Preço,Garantia Disp,Deságio,Limite Boleta,Garantia Exigida,Resultado Garantia,Volume Boleta,Resultado Boleta
0,2039221,C,100,PETR4,28.0,100000.0,0.05,100000,140.0,Aprovado,2800.0,Aprovado
1,44534,C,100,PETR4,28.0,120.0,0.05,100000,140.0,Rejeitado,2800.0,Aprovado
2,226765,C,10000,PETR4,28.0,20000.0,0.05,100000,14000.0,Aprovado,280000.0,Rejeitado
3,56542,C,5000,MGLU3,7.0,20000.0,0.10,80000,3500.0,Aprovado,35000.0,Aprovado
4,56564,C,15000,MGLU3,7.0,10000.0,0.10,80000,10500.0,Rejeitado,105000.0,Rejeitado
5,226765,C,12000,MGLU3,7.0,100000.0,0.10,80000,8400.0,Aprovado,84000.0,Rejeitado
6,2039221,V,100,PETR4,28.0,100000.0,0.05,100000,140.0,Aprovado,2800.0,Aprovado
7,44534,V,100,PETR4,28.0,120.0,0.05,100000,140.0,Rejeitado,2800.0,Aprovado
8,226765,V,10000,PETR4,28.0,20000.0,0.05,100000,14000.0,Aprovado,280000.0,Rejeitado
9,56542,V,5000,MGLU3,7.0,20000.0,0.10,80000,3500.0,Aprovado,35000.0,Aprovado
10,56564,V,15000,MGLU3,7.0,10000.0,0.10,80000,10500.0,Rejeitado,105000.0,Rejeitado
11,226765,V,12000,MGLU3,7.0,100000.0,0.10,80000,8400.0,Aprovado,84000.0,Rejeitado

In [ ]:
def analisar_ordens(nome_arquivo):
    df = organizar_ordens(nome_arquivo)
    
    qtde_rejeitadas = 0
    qtde_enviadas = 0
    ordens_rejeitadas = []
    ordens_aprovadas =[]
    i = 1
    
    # Checagem das ordens
    for index, row in df.iterrows():
        # Checagem garantia
        if row['Resultado Garantia'] == 'Rejeitado':
            print(f'Ordem da linha {i} do cliente {row["Código"]} foi \033[31mrejeitada\033[m, pois garantia exigida de {row["Garantia Exigida"]} ultrapassou a garantia disponível de {row["Garantia Disp"]}!\n')
            ordens_rejeitadas.append(i)
            i += 1
        # Checagem volume boleta    
        elif row['Resultado Boleta'] == 'Rejeitado':
            print(f'Ordem da linha {i} do cliente {row["Código"]} foi \033[31mrejeitada\033[m, pois o volume financeiro da boleta de {row["Volume Boleta"]} ultrapassou o limite máximo definido de {row["Limite Boleta"]}\n')
            ordens_rejeitadas.append(i)
            i += 1
        # Caso chegar aqui, ordem aprovada!    
        else:
            print(f'\033[32mOrdem da linha {i} do cliente {row["Código"]} foi enviada com sucesso!\033[m\n')
            ordens_aprovadas.append(i)
            i += 1
    
    # Dict com ordens aprovadas e reprovadas para facilitar usos futuros e localização no df original
    resultado_ordens = {'Aprovadas': ordens_aprovadas, 'Reprovadas': ordens_rejeitadas}
    
    return resultado_ordens

In [ ]:
analisar_ordens('Ex_Clientes_Ordens.txt')